Install pytest-timeout by separate step

diff --git a/.github/workflows/conda-package.yml b/.github/workflows/conda-package.yml
--- a/.github/workflows/conda-package.yml
+++ b/.github/workflows/conda-package.yml
@@ -216,6 +216,11 @@ jobs:
           sudo apt-get update --fix-missing
           sudo apt-get install -y gdb
 
+
+      - name: Install pytest-timeout
+        run: |
+          pip install pytest-timeout
+
       - name: Run tests
         if: env.rerun-tests-on-failure != 'true'
         run: |
@@ -243,22 +248,22 @@ jobs:
       #         python -m pytest -n auto -sv --pyargs ${{ env.package-name }}.tests.third_party.cupy
       #       fi
 
-      - name: Run tests with GDB
-        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
-        with:
-          timeout_minutes: ${{ env.rerun-tests-timeout }}
-          max_attempts: ${{ env.rerun-tests-max-attempts }}
-          retry_on: any
-          command: |
-            . $CONDA/etc/profile.d/conda.sh
-            . $CONDA/etc/profile.d/mamba.sh
-            mamba activate ${{ env.test-env-name }}
+      # - name: Run tests with GDB
+      #   uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
+      #   with:
+      #     timeout_minutes: ${{ env.rerun-tests-timeout }}
+      #     max_attempts: ${{ env.rerun-tests-max-attempts }}
+      #     retry_on: any
+      #     command: |
+      #       . $CONDA/etc/profile.d/conda.sh
+      #       . $CONDA/etc/profile.d/mamba.sh
+      #       mamba activate ${{ env.test-env-name }}
 
-            if [[ "${{ matrix.python }}" == "${{ env.python-ver-test-all-dtypes }}" ]]; then
-              export DPNP_TEST_ALL_INT_TYPES=1
-            else
-              timeout 25m gdb --batch -ex run -ex 'info sharedlibrary' -ex 'set print elements 20000' -ex thread apply all bt --args python -m pytest -n auto -ra --pyargs ${{ env.package-name }}.tests || true
-            fi
+      #       if [[ "${{ matrix.python }}" == "${{ env.python-ver-test-all-dtypes }}" ]]; then
+      #         export DPNP_TEST_ALL_INT_TYPES=1
+      #       else
+      #         timeout 25m gdb --batch -ex run -ex 'info sharedlibrary' -ex 'set print elements 20000' -ex thread apply all bt --args python -m pytest -n auto -ra --pyargs ${{ env.package-name }}.tests || true
+      #       fi
 
       - name: Run tests with timeout
         uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
@@ -270,7 +275,6 @@ jobs:
             . $CONDA/etc/profile.d/conda.sh
             . $CONDA/etc/profile.d/mamba.sh
             mamba activate ${{ env.test-env-name }}
-            pip install pytest-timeout
 
             if [[ "${{ matrix.python }}" == "${{ env.python-ver-test-all-dtypes }}" ]]; then
               export DPNP_TEST_ALL_INT_TYPES=1
